# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('area_id', models.CharField(max_length=256)),
                ('Description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('switch', models.CharField(max_length=256)),
                ('pin', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('device_id', models.CharField(max_length=128)),
                ('serial_id', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('customer', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('install_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('pin_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('switch_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='device_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='event',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.CharField(default=datetime.datetime(2016, 6, 13, 21, 13, 30, 521635, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 6, 13, 21, 13, 43, 329178, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='time_date',
            field=models.CharField(max_length=256),
        ),
    ]
