# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0004_auto_20160614_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='device',
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.OneToOneField(default=1, to='guitron.Device'),
            preserve_default=False,
        ),
    ]
