# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0005_auto_20160614_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_data',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='serial_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='device',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_date',
        ),
        migrations.AddField(
            model_name='device',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guitron.Event'),
            preserve_default=False,
        ),
    ]
