# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0007_auto_20160614_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guitron.Event'),
            preserve_default=False,
        ),
    ]
