# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0008_auto_20160614_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
