# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0009_auto_20160614_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='event',
            new_name='event_data',
        ),
    ]
