# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0012_remove_device_event_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='name',
        ),
    ]
