# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0013_remove_pin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='device',
        ),
    ]
