# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0015_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_id', models.CharField(max_length=256)),
            ],
        ),
    ]
