# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0016_gadget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_data',
        ),
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.CharField(default=datetime.datetime(2016, 6, 14, 6, 54, 10, 812471, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gadget',
            name='ip_address',
            field=models.CharField(default=datetime.datetime(2016, 6, 14, 6, 54, 21, 188088, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
