# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0017_auto_20160614_0654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
