# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0020_gadget_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Monitor',
        ),
        migrations.RenameField(
            model_name='gadget',
            old_name='status',
            new_name='monitor',
        ),
    ]
