# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0021_auto_20160614_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.CharField(max_length=256)),
                ('off', models.CharField(max_length=256)),
            ],
        ),
    ]
