# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0023_pin_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='pin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='guitron.Pin'),
        ),
    ]
