# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0024_switch_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadget_id', models.CharField(max_length=256)),
                ('ip_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='gadget',
            name='monitor',
        ),
    ]
