# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0025_auto_20160615_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('controller', models.PositiveIntegerField(default=0)),
                ('pin', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componet', models.PositiveIntegerField(default=0)),
                ('time', models.DateField(auto_now_add=True, db_index=True)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
            ],
        ),
        migrations.RemoveField(
            model_name='controller',
            name='gadget_id',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='controller',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
