# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0026_auto_20160616_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componet',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitron.Controller'),
        ),
        migrations.AlterField(
            model_name='event',
            name='componet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitron.Componet'),
        ),
    ]
