# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0027_auto_20160616_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
