# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0028_controller_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Componet',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='componet',
            new_name='component',
        ),
    ]
