# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0028_controller_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='id',
        ),
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
