# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0029_auto_20160621_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
