# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0030_auto_20160623_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
