# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guitron', '0031_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('time', models.DateField(auto_now_add=True, db_index=True)),
                ('completed', models.BooleanField(verbose_name=False)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guitron.Component')),
            ],
        ),
    ]
